USE group126;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS photo;

CREATE TABLE album
(
	albumid INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(50) NOT NULL,
	created DATE NOT NULL,
	lastupdated DATE NOT NULL,
	permission VARCHAR(20) NOT NULL
);

CREATE TABLE photo
(
	sequencenum INT PRIMARY KEY,
	url VARCHAR(255) NOT NULL,
	filename VARCHAR(255) NOT NULL,
	caption VARCHAR(255),
	datetaken DATE NOT NULL
);

SET FOREIGN_KEY_CHECKS=1;
